#!/usr/bin/perl 
################################################################
# This program generates a Makefile for compiling on Digital
# Unix using a DEC f90 compiler.  It is invoked by typing
# makemake *.f90 *.F
################################################################

@fortranfiles = @ARGV;
my @f77files  = <*.F>;
my @fileinfo;
my $fileno = 0;
my @sortedfiles;
my @filelist;
my @librarylist;

# Get the list of relevant fortran files.  This list is generated
# by looking at the "music.f90" file and then recusively, generating
# a list of modules it uses
push(@filelist, @f77files);
push(@filelist, "music.f90");
$nmods = getUseMods("music.f90", \@filelist, \@librarylist);

# Get the modules used in each file contained in filelist.  This
# could have been generated within "getUseMods" but I am recycling
# code
foreach $f (@filelist)
{
    unless(isListElem($f, \@librarylist))
    {
	get_modules($f,\@librarylist);
    }
}

#sort the $fileno array based on the number of modules
#each element has
@sortedfiles = sort {$$a{modcount} <=> $$b{modcount}} @fileinfo;

# Generate the makefile by first dumping the header and then
# the dependency list
dump_makefile_header(\@sortedfiles, $fileno);
dump_dependency(\@sortedfiles, $fileno);

#######################################################################
#######################################################################


#########################################################################
# Prints the header of the makefile
#########################################################################
sub dump_makefile_header(\@$)
{
    my $sortedfiles = shift;
    my $fileno = shift;  
    my ($sourcefile, $objectfile, $f);

    print STDOUT <<'EOF';
# Use this Makefile with gmake
FC = f90
CMD = music

#old flags
FFLAGS = -g -cpp -C -ladebug -check underflow -check overflow 
#FFLAGS = -cpp
F90FLAGS = -u -std95


# Define the optimizing flags for the compiler platform
OFLAGS =  -fast

# Define the free form flags for the platform
FREEFLAGS = -free

# Implicit rules for handling src files
%.o : %.f90
	$(FC) $(FFLAGS) $(F90FLAGS) $(OFLAGS) -c $<
%.o : %.F
	$(FC) $(FFLAGS) $(OFLAGS) -c $<

EOF

    print "OBJECTS = ";
    $totallength = 12;
    for($f=0; $f<$fileno; $f++)
    {
	$objectfile = $$sortedfiles[$f]{filename};
	$objectfile =~ s/(.*?\.)f90/$1o/i;
	$objectfile =~ s/(.*?\.)F/$1o/;
	$totallength = $totallength + length($objectfile);
	if ($totallength > 70)
	{
	    print "\\\n";
	    $totallength = 8;
	}
	print "$objectfile ";
    }
    print "\n\n";

    print STDOUT <<'EOF';
$(CMD) : $(OBJECTS)
	$(FC) $(FFLAGS) $(OFLAGS) $(OBJECTS)  -o ../$(CMD)

dec : $(OBJECTS)
	$(FC) $(FFLAGS) $(OFLAGS) $(OBJECTS) -o ../$(CMD)

clean:
	/bin/rm -f *.o *.i *.mod a.out make.log

cleano:
	rm -f *.o *.i 


depend : 
	makemake *.f90 *.F > Makefile 

EOF
}
			 
####################################################################
# Prints the dependecy list
####################################################################
sub dump_dependency(\@$)
{
    my $sortedfiles = shift;
    my $fileno = shift;  
    my ($sourcefile, $f);
    
    for($f=0; $f < $fileno; $f++)
    {
	$sourcefile = $$sortedfiles[$f]{filename};
	$rootname   = (split(/\./,$sourcefile, 2))[0];
	$objfile    = $rootname.".o";
	printf("%-25s :", $objfile);
	for($i=0; $i<$$sortedfiles[$f]{modcount};$i++)
	{
	    print(" $$sortedfiles[$f]{modarray}[$i].o");
	}
	print("\n");
    }
}


########################################################################
# Gets the modules used in a file
########################################################################
sub get_modules($\@)
{
    my $filename = shift;
    my $librarymods = shift;
    my $nmodules = 0;
    my @modules;
    my $modfile;

    open(FILE, $filename) || 
	return;

    while(defined($nextline = get_nextline(*FILE)))
    {
	if ($nextline =~ /^\s*use (.*?)[,\s]/i)
	{
	    # Do not add the module if it is a library module
	    $modfile = $1.".f90";
	    next if (isListElem($modfile, $librarymods));
		
	    #Check for duplicates
	    for($i=0; $i<$nmodules; $i++)
	    {
		last if ($modules[$i] eq $1);
	    }

	    # No duplicates found
	    if ($i == $nmodules)
	    {
		$nmodules++;
		push(@modules, $1);
	    }
	}
    }
    $fileinfo[$fileno] = {filename => $filename,
			    modcount => $nmodules,
			    modarray => \@modules};
    $fileno++;
}


#######################################################
# This takes a filename and generates an array of the
# module usage for that file, recursively
#######################################################
sub getUseMods($\@\@)
{
    my ($filename)    = shift;
    my ($usefilelist) = shift;
    my ($libraryfile) = shift;
    my ($nfiles, $line, $usedmod, $usedfile, $found);
    my (@lines);
    
    # Open the file and read the lines
    unless(open(FILE, $filename))
    {
	push(@$libraryfile, $filename);
    }

    @lines = <FILE>;

    foreach $line (@lines)
    {
	# Check if the line is a "Use" line.  If so
	# open the module being used and recusively
	# get the modules it is using...
	if (isUse($line))
	{
	    $line =~ /^\s*use\s+(\w*)/i;
	    $usedmod = $1;
	    $usedfile = $usedmod.".f90";

	    unless (isListElem($usedfile, $usefilelist))
	    {
		push(@$usefilelist, $usedfile);
		getUseMods($usedfile, $usefilelist, $libraryfile);
	    }
	}
    }
    close(FILE);
    return(@$usefilelist);
}


#######################################################################
# Checks to see if an element is present in the list
#######################################################################
sub isListElem($\@)
{
    my $element = shift;
    my $list = shift;

    foreach $f (@$list)
    {
	if ($element eq $f)
	{
	    return(1);
	}
    }
    return(0);
}


########################################################################
#Gets the next non-comment line
########################################################################
sub get_nextline(*)
{
    local(*FILE) = shift;
    
    $inputline = <FILE>;

    while(defined($inputline) && isComment($inputline))
    {
	$inputline = <FILE>;
    }
    return($inputline);
}


##################################################################
# Takes in a line and checks whether the line is a "USE" statement
##################################################################
sub isUse($)
{
    my($line) = shift;

    if (isComment($line))
    {
	return(0);
    }
    if ($line =~ /^\s*use\s+\w+/i)
    {
	return(1);
    }
}


########################################################################
#Checks whether a line is a comment
#Anything starting with a !, c or *
#is a comment
########################################################################
sub isComment($)
{
    my($input) = shift;

    if ($input =~ /(^[c!*\n])|(^\s*!)/i)
    {
	return(1);
    }
    return(0);
}










