#!/bin/csh

echo 'setting environment variables'

setenv EMAPDIR ./potentials/pmaps
setenv PMAPDIR ./potentials/pmaps
setenv SMAPDIR ./potentials/pmaps
setenv ATOMSDIR ./potentials/atoms
setenv MOLSDIR ./potentials/molecules

echo "-"
echo "-"
echo '---- REFERENCE OUTPUT ------------------------'
tail -70 output_reference > .temp0
grep -a -A 23 'MD Step' .temp0
grep -a 'Main Program   Time' .temp0

echo '----------------------------'
echo '----------------------------'
echo '----------------------------'
echo "-"
echo "-"
echo '---- CURRENT MUSIC OUTPUT --------------------'

./md.exe test004.ctr >& out
tail -70 out  > .temp0
grep -a -A 23 'MD Step' .temp0
grep -a 'Main Program   Time' .temp0

echo  "Use 'diff out output_reference' for a detialed comparison"
